# Generated by Django 4.2.29 on 2026-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspacemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='max_seats',
            field=models.PositiveIntegerField(default=15, help_text='Maximum member seats allocated to this workspace (teams of 5-15, expandable).'),
        ),
    ]
