# Generated by Django 4.2.29 on 2026-09-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace_max_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='storage_quota_mb',
            field=models.PositiveIntegerField(default=50, help_text='Allocated storage quota in megabytes (MB) for Supabase Free Tier (default 50 MB).'),
        ),
    ]
