# Generated by Django 4.2.29 on 2026-09-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_workspace_storage_quota_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembership',
            name='functional_role',
            field=models.CharField(blank=True, default='', help_text='Functional designation/job title, e.g. Frontend Developer, Backend Developer, Support Engineer', max_length=100),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='reporting_to',
            field=models.ForeignKey(blank=True, help_text='The person this member reports to within the workspace (defaults to Workspace Owner / Admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='workspaces.workspacemembership'),
        ),
        migrations.AddField(
            model_name='workspacemembership',
            name='role_tag',
            field=models.CharField(blank=True, default='', help_text='Role domain tag, e.g. Frontend, Backend, Support, Design, DevOps, QA, Product', max_length=50),
        ),
    ]
