# Generated by Django 4.2.29 on 2026-09-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspacemembership_functional_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='architecture_notes',
            field=models.TextField(blank=True, default='', help_text='Architecture and engineering guidelines for the workspace'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='project_scope',
            field=models.TextField(blank=True, default='', help_text='Comprehensive project scope and initiative details'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='security_mode',
            field=models.CharField(blank=True, default='Strict RBAC', help_text='Security isolation mode (e.g. Strict RBAC, Enterprise Multi-Tenant)', max_length=50),
        ),
        migrations.AddField(
            model_name='workspace',
            name='storage_provider',
            field=models.CharField(blank=True, default='Supabase Storage', help_text='File and asset storage provider', max_length=50),
        ),
        migrations.AddField(
            model_name='workspace',
            name='tech_stack',
            field=models.CharField(blank=True, default='Python 3.12, Django 5.x, PostgreSQL, Supabase Storage, Tailwind CSS, Alpine.js, WebRTC', help_text='Comma-separated tech stack badges', max_length=500),
        ),
    ]
