# Generated by Django 4.2.29 on 2026-09-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_workspace_architecture_notes_workspace_project_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='logo',
            field=models.CharField(blank=True, default='', help_text='Supabase storage URL, storage path, or external link for workspace logo', max_length=1024),
        ),
    ]
