# Generated by Django 4.2.29 on 2026-09-30 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0007_workspace_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('task.create', 'Create Task'), ('task.edit', 'Edit Task'), ('task.delete', 'Delete Task'), ('bug.create', 'Raise Bug'), ('bug.edit', 'Edit Bug'), ('file.upload', 'Upload File'), ('calendar.create', 'Create Event'), ('meeting.create', 'Schedule Meeting'), ('workspace.access', 'Workspace Access'), ('custom', 'Custom Action')], db_index=True, default='task.create', max_length=50)),
                ('target_resource_id', models.CharField(blank=True, default='', help_text='Optional ID or code of specific task, bug, file, or resource', max_length=255)),
                ('reason', models.TextField(help_text='Detailed justification for access request')),
                ('goal_description', models.TextField(blank=True, default='', help_text='What are you trying to accomplish (required for emergency/action requests)')),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], db_index=True, default='NORMAL', max_length=20)),
                ('evidence_url', models.URLField(blank=True, default='', max_length=1024)),
                ('evidence_file', models.CharField(blank=True, default='', help_text='Storage path or reference to uploaded evidence screenshot', max_length=1024)),
                ('requested_duration', models.CharField(choices=[('ONE_TIME', 'One-time Action'), ('1_HOUR', '1 Hour'), ('4_HOURS', '4 Hours'), ('TODAY', 'Today (Until Midnight)'), ('CUSTOM', 'Custom Duration')], default='1_HOUR', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_global_access_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_access_requests', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_access_requests', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='workspaceaccessrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='TemporaryAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('target_resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('access_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='workspaces.globalaccessrequest')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_temporary_access_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_access_grants', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_access_grants', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'workspace', 'action', 'expires_at'], name='workspaces__user_id_033d03_idx'), models.Index(fields=['expires_at', 'is_revoked'], name='workspaces__expires_120dd8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='globalaccessrequest',
            index=models.Index(fields=['status', 'urgency', '-created_at'], name='workspaces__status_6471bd_idx'),
        ),
        migrations.AddIndex(
            model_name='globalaccessrequest',
            index=models.Index(fields=['workspace', 'action', 'status'], name='workspaces__workspa_190def_idx'),
        ),
        migrations.AddIndex(
            model_name='globalaccessrequest',
            index=models.Index(fields=['user', 'status'], name='workspaces__user_id_f7f4c4_idx'),
        ),
    ]
