# Generated by Django 4.2.29 on 2026-09-14 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('meetings', 'Meet Hub'), ('chat', 'Team Chat'), ('calendars', 'Calendar & Agenda'), ('files', 'Files & Storage'), ('tasks', 'Tasks & Kanban'), ('bugs', 'Bug Tracker'), ('notifications', 'Notifications'), ('timetracking', 'Time Tracking')], help_text='Unique programmatic identifier for the module.', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable module name.', max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Under Maintenance'), ('COMING_SOON', 'Coming Soon')], db_index=True, default='AVAILABLE', help_text='Current operational availability.', max_length=30)),
                ('public_message', models.CharField(blank=True, default='', help_text='Public status message displayed to all users.', max_length=255)),
                ('maintenance_explanation', models.TextField(blank=True, default='', help_text='Optional technical or operational explanation for administrators.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Administrator who last updated this module status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_module_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Status',
                'verbose_name_plural': 'Module Statuses',
                'ordering': ['name'],
            },
        ),
    ]
