# Generated by Antigravity for AetherSpace Module Maintenance System

from django.db import migrations


def seed_module_statuses(apps, schema_editor):
    ModuleStatus = apps.get_model('core', 'ModuleStatus')

    modules = [
        {
            'module_key': 'meetings',
            'name': 'Meet Hub',
            'status': 'MAINTENANCE',
            'public_message': 'Meet Hub is temporarily unavailable while we complete improvements.',
            'maintenance_explanation': 'Owner QA confirmed real-time WebRTC audio/video meeting functionality is not production-ready. Locked under global maintenance until signaling pipeline is upgraded.',
        },
        {
            'module_key': 'chat',
            'name': 'Team Chat',
            'status': 'AVAILABLE',
            'public_message': 'Team Chat is fully operational.',
            'maintenance_explanation': '',
        },
        {
            'module_key': 'calendars',
            'name': 'Calendar & Agenda',
            'status': 'AVAILABLE',
            'public_message': 'Calendar & Agenda is fully operational.',
            'maintenance_explanation': '',
        },
        {
            'module_key': 'files',
            'name': 'Files & Storage',
            'status': 'AVAILABLE',
            'public_message': 'Files & Storage is fully operational.',
            'maintenance_explanation': '',
        },
        {
            'module_key': 'tasks',
            'name': 'Tasks & Kanban',
            'status': 'AVAILABLE',
            'public_message': 'Tasks & Kanban is fully operational.',
            'maintenance_explanation': '',
        },
        {
            'module_key': 'bugs',
            'name': 'Bug Tracker',
            'status': 'AVAILABLE',
            'public_message': 'Bug Tracker is fully operational.',
            'maintenance_explanation': '',
        },
        {
            'module_key': 'notifications',
            'name': 'Notifications',
            'status': 'AVAILABLE',
            'public_message': 'Notifications are fully operational.',
            'maintenance_explanation': '',
        },
        {
            'module_key': 'timetracking',
            'name': 'Time Tracking',
            'status': 'AVAILABLE',
            'public_message': 'Time Tracking is fully operational.',
            'maintenance_explanation': '',
        },
    ]

    for item in modules:
        ModuleStatus.objects.update_or_create(
            module_key=item['module_key'],
            defaults={
                'name': item['name'],
                'status': item['status'],
                'public_message': item['public_message'],
                'maintenance_explanation': item['maintenance_explanation'],
            }
        )


def rollback_module_statuses(apps, schema_editor):
    ModuleStatus = apps.get_model('core', 'ModuleStatus')
    ModuleStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_module_statuses, rollback_module_statuses),
    ]
