# Generated by Django 4.2.29 on 2026-09-11 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0004_subtask'),
        ('bugs', '0003_bug_linked_task_bug_bugs_bug_linked__560d9d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
        ('workspaces', '0003_workspace_max_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_type', models.CharField(choices=[('MEETING', 'Meeting'), ('MILESTONE', 'Milestone'), ('TASK_DEADLINE', 'Task Deadline'), ('WORK_SESSION', 'Work Session'), ('GENERAL', 'General Event')], db_index=True, default='GENERAL', max_length=30)),
                ('calendar_category', models.CharField(choices=[('WORKSPACE', 'Workspace Calendar'), ('PERSONAL', 'My Calendar')], default='WORKSPACE', max_length=20)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(db_index=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('repeat', models.CharField(choices=[('NONE', 'Does not repeat'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=20)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='UPCOMING', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_link', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('linked_bug', models.ForeignKey(blank=True, help_text='Optional bug fix deadline or triage this event is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='bugs.bug')),
                ('linked_meeting', models.ForeignKey(blank=True, help_text='Optional video/audio conference linked to this calendar event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='meetings.meeting')),
                ('linked_task', models.ForeignKey(blank=True, help_text='Optional task deadline or story this event is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='tasks.task')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TENTATIVE', 'Tentative')], default='INVITED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='calendars.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['workspace', 'start_at'], name='calendars_c_workspa_9358bb_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['workspace', 'event_type'], name='calendars_c_workspa_55320b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['workspace', 'status'], name='calendars_c_workspa_3dd83f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['created_by', 'start_at'], name='calendars_c_created_1fcda0_idx'),
        ),
    ]
