# Generated by Django 4.2.29 on 2026-09-23 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='agenda',
            field=models.TextField(blank=True, default='', help_text='Formatted event agenda, discussion topics, or meeting notes.'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reference_links',
            field=models.JSONField(blank=True, default=list, help_text="List of external reference links [{'title': '...', 'url': '...'}]"),
        ),
        migrations.CreateModel(
            name='CalendarEventAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='calendars.calendarevent')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_attachments', to='files.storedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
