# Generated by Django 4.2.29 on 2026-09-12 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0005_workspacemembership_functional_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=255)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('WARNING', 'Warning')], default='SUCCESS', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='admin_panel_action_a0d9ca_idx'), models.Index(fields=['target_type', '-created_at'], name='admin_panel_target__70e3ae_idx'), models.Index(fields=['actor', '-created_at'], name='admin_panel_actor_i_d51a91_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info'), ('RESOLVED', 'Resolved')], db_index=True, default='INFO', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('STORAGE', 'Storage & Files'), ('SECURITY', 'Security & Auth'), ('BUGS', 'Critical Bugs'), ('ACCESS', 'Workspace Requests'), ('SYSTEM', 'System & Runtime')], db_index=True, default='SYSTEM', max_length=50)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_admin_alerts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_alerts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['is_resolved', '-created_at'],
                'indexes': [models.Index(fields=['severity', 'is_resolved', '-created_at'], name='admin_panel_severit_f8b94a_idx'), models.Index(fields=['category', 'is_resolved'], name='admin_panel_categor_57053f_idx')],
            },
        ),
    ]
