# Generated by Django 4.2.29 on 2026-09-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner',
            field=models.CharField(blank=True, default='', help_text='Supabase storage path, image URL, or gradient preset', max_length=1024),
        ),
    ]
