# Generated by Django 4.2.29 on 2026-09-13 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_existing_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    counter = 20000
    for user in User.objects.all():
        if not getattr(user, 'contributor_id', None):
            user.contributor_id = f"{counter}C"
            counter += 1
        if getattr(user, 'approval_status', None) == 'PENDING':
            user.approval_status = 'APPROVED'
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', help_text='Account approval state: Pending, Approved, Rejected, Suspended', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='contributor_id',
            field=models.CharField(blank=True, help_text='Unique 5-digit numeric identifier with C suffix (e.g. 26457C)', max_length=10),
        ),
        migrations.RunPython(backfill_existing_users, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='contributor_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique 5-digit numeric identifier with C suffix (e.g. 26457C)', max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['approval_status'], name='accounts_us_approva_c9c17e_idx'),
        ),
    ]
