# Generated by Django 4.2.29 on 2026-09-09 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
        ('workspaces', '0003_workspace_max_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_code', models.CharField(db_index=True, help_text='Human-facing identifier, e.g. meet-k7xp-2m9q', max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('meeting_type', models.CharField(choices=[('INSTANT', 'Instant Meeting'), ('STANDUP', 'Daily Standup'), ('SPRINT_PLANNING', 'Sprint Planning'), ('RETROSPECTIVE', 'Retrospective'), ('CHAT_CALL', 'Chat Call'), ('GENERAL', 'General Discussion')], db_index=True, default='GENERAL', max_length=30)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live Now'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('external_room_url', models.URLField(blank=True, default='')),
                ('passcode', models.CharField(blank=True, default='', max_length=20)),
                ('is_audio_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='chat.channel')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('HOST', 'Host'), ('ATTENDEE', 'Attendee')], default='ATTENDEE', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['meeting', 'left_at'], name='meetings_me_meeting_89c92c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeetingInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['workspace', 'status'], name='meetings_me_workspa_d9a3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['workspace', 'scheduled_start'], name='meetings_me_workspa_f9a0de_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_code'], name='meetings_me_meeting_2e5ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['workspace', 'created_at'], name='meetings_me_workspa_b66d53_idx'),
        ),
    ]
