# Generated by Django 4.2.29 on 2026-09-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingparticipant',
            name='is_hand_raised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
