# Generated by Django 4.2.29 on 2026-09-22 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0006_workspace_architecture_notes_workspace_project_scope_and_more'),
        ('tasks', '0005_taskattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Sprint 4 or Q4 Release Sprint', max_length=100)),
                ('goal', models.TextField(blank=True, default='', help_text='Key objective for this sprint')),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], db_index=True, default='PLANNING', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sprints', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='sprint_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.sprint'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['workspace', 'status'], name='tasks_sprin_workspa_16d57c_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['workspace', '-created_at'], name='tasks_sprin_workspa_01a565_idx'),
        ),
    ]
