# Generated by Django 4.2.29 on 2026-09-26 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_sprint_task_sprint_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_code', models.CharField(db_index=True, help_text='Code review reference identifier, e.g. CR-619347', max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('github_pr_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_REVIEW', 'In Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('MERGED', 'Merged'), ('CLOSED', 'Closed')], db_index=True, default='REQUESTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_reviews_requested', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_reviews', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', 'status'], name='tasks_coder_task_id_eaf6ea_idx'), models.Index(fields=['task', '-created_at'], name='tasks_coder_task_id_a99a6c_idx'), models.Index(fields=['review_code'], name='tasks_coder_review__a1048d_idx')],
            },
        ),
    ]
