# Generated by Django 4.2.29 on 2026-09-26 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0004_bugattachment'),
        ('tasks', '0007_codereviewrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereviewrequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_reviews_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to='bugs.bug'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='code_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='tasks.codereviewrequest'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='comment_type',
            field=models.CharField(choices=[('USER', 'User Comment'), ('SYSTEM', 'System Event')], db_index=True, default='USER', max_length=20),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='system_event_type',
            field=models.CharField(blank=True, choices=[('TASK_CREATED', 'Task Created'), ('BUG_ATTACHED', 'Bug Attached'), ('BUG_DETACHED', 'Bug Detached'), ('CODE_REVIEW_REQUESTED', 'Code Review Requested'), ('CODE_REVIEW_STATUS_CHANGED', 'Code Review Status Changed'), ('REVIEWER_ASSIGNED', 'Reviewer Assigned')], db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
