# Generated by Django 4.2.29 on 2026-09-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_codereviewrequest_reviewer_taskcomment_bug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('PLANNING', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('PRIORITY_CHANGED', 'Priority Changed'), ('UPDATED', 'Updated'), ('COMMENTED', 'Commented'), ('BUG_LINKED', 'Bug Attached'), ('BUG_UNLINKED', 'Bug Detached')], default='UPDATED', max_length=50),
        ),
    ]
