# Generated by Django 4.2.29 on 2026-09-11 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_workspace_max_seats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('color', models.CharField(default='amber', max_length=30)),
                ('is_starred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='files.folder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('external_url', models.URLField(blank=True, default='', max_length=1000)),
                ('is_external_link', models.BooleanField(default=False)),
                ('mime_type', models.CharField(blank=True, default='application/octet-stream', max_length=120)),
                ('category', models.CharField(choices=[('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('SPREADSHEET', 'Spreadsheet'), ('PRESENTATION', 'Presentation'), ('CODE', 'Code / Text'), ('ARCHIVE', 'Archive'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('URL_LINK', 'External Link'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.folder')),
                ('last_accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_accessed_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('external_url', models.URLField(blank=True, default='', max_length=1000)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.storedfile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('VIEW', 'Can View'), ('EDIT', 'Can Edit')], default='VIEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.storedfile')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_file_shares', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_file_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='files.storedfile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='files.storedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['workspace', 'is_trashed', '-updated_at'], name='files_store_workspa_418121_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['workspace', 'folder', 'is_trashed'], name='files_store_workspa_cb25c7_idx'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['workspace', 'category'], name='files_store_workspa_4ad84b_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('workspace', 'parent', 'name'), name='unique_folder_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='fileshare',
            constraint=models.UniqueConstraint(fields=('file', 'shared_with'), name='unique_file_user_share'),
        ),
    ]
