# Generated by Django 4.2.29 on 2026-09-13 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0005_workspacemembership_functional_role_and_more'),
        ('tasks', '0004_subtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Total elapsed duration in seconds.')),
                ('is_running', models.BooleanField(db_index=True, default=False)),
                ('entry_type', models.CharField(choices=[('TIMER', 'Live Timer'), ('MANUAL', 'Manual Entry')], default='TIMER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['workspace', 'user', '-started_at'], name='timetrackin_workspa_829e4b_idx'), models.Index(fields=['workspace', 'is_running'], name='timetrackin_workspa_f102d0_idx'), models.Index(fields=['user', 'is_running'], name='timetrackin_user_id_9dc80a_idx')],
            },
        ),
    ]
