# Generated by Django 4.2.29 on 2026-09-19 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='accumulated_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Total accumulated active running seconds (excluding paused intervals).'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='last_resumed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], db_index=True, default='COMPLETED', max_length=15),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['workspace', 'status'], name='timetrackin_workspa_941075_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'status'], name='timetrackin_user_id_c03c73_idx'),
        ),
    ]
