# Generated by Django 4.2.29 on 2026-09-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0002_timeentry_accumulated_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='last_resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
