# Generated by Django 4.2.29 on 2026-09-12 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0004_workspace_storage_quota_mb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('TASK', 'Task'), ('BUG', 'Bug'), ('MENTION', 'Mention'), ('MEETING', 'Meeting'), ('FILE', 'File'), ('WORKSPACE', 'Workspace'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=20)),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_DUE_SOON', 'Task Due Soon'), ('BUG_REPORTED', 'Bug Reported'), ('BUG_ASSIGNED', 'Bug Assigned'), ('BUG_STATUS_CHANGED', 'Bug Status Changed'), ('CHAT_MENTION', 'Chat Mention'), ('CHAT_DM', 'Direct Message'), ('MEETING_INVITE', 'Meeting Invite'), ('FILE_SHARED', 'File Shared'), ('ROLE_UPDATED', 'Role Updated'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('action_url', models.CharField(blank=True, default='', help_text='Internal URL to navigate to when the notification is clicked.', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who triggered the notification, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, help_text='Workspace context where the event occurred, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['workspace', 'recipient', 'category'], name='notificatio_workspa_6015ed_idx'), models.Index(fields=['recipient', 'category', 'is_read'], name='notificatio_recipie_130037_idx')],
            },
        ),
    ]
