# Generated by Django 4.2.29 on 2026-09-07 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bug_code', models.CharField(db_index=True, help_text='Human-facing 6-digit bug identifier with prefix, e.g. B-882316', max_length=12, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('steps_to_reproduce', models.TextField(blank=True, default='', help_text='Numbered steps to reproduce the issue')),
                ('expected_result', models.TextField(blank=True, default='')),
                ('actual_result', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('severity', models.CharField(choices=[('SEV1', 'Sev 1 - Critical / Blocker'), ('SEV2', 'Sev 2 - Major'), ('SEV3', 'Sev 3 - Moderate'), ('SEV4', 'Sev 4 - Minor')], db_index=True, default='SEV3', max_length=20)),
                ('environment', models.CharField(choices=[('PRODUCTION', 'Production'), ('STAGING', 'Staging'), ('DEVELOPMENT', 'Development'), ('QA', 'QA / Testing')], default='STAGING', max_length=20)),
                ('module', models.CharField(choices=[('Authentication', 'Authentication'), ('Dashboard', 'Dashboard'), ('Tasks', 'Tasks'), ('Bug Tracking', 'Bug Tracking'), ('Files', 'Files & Storage'), ('Meetings', 'Meet Hub'), ('Chat', 'Chat & Messaging'), ('Reports', 'Reports'), ('UI/UX', 'UI / UX'), ('Settings', 'Settings'), ('Other', 'Other')], default='Other', max_length=50)),
                ('browser_device', models.CharField(blank=True, default='', help_text='e.g. Chrome 124 / Windows 11', max_length=255)),
                ('sprint', models.CharField(blank=True, default='Sprint 01', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('labels', models.CharField(blank=True, default='', help_text='Comma-separated labels, e.g. login, server-error', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_bugs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_comments', to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bugs.bug')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('PRIORITY_CHANGED', 'Priority Changed'), ('SEVERITY_CHANGED', 'Severity Changed'), ('COMMENTED', 'Commented'), ('ATTACHMENT_ADDED', 'Attachment Added'), ('UPDATED', 'Updated')], default='UPDATED', max_length=50)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_activities', to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bugs.bug')),
            ],
            options={
                'verbose_name_plural': 'Bug activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['workspace', 'status'], name='bugs_bug_workspa_9d004b_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['workspace', 'priority'], name='bugs_bug_workspa_d5825d_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['workspace', 'severity'], name='bugs_bug_workspa_e7bc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['assignee', 'status'], name='bugs_bug_assigne_a34820_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['workspace', 'created_at'], name='bugs_bug_workspa_2d5002_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['bug_code'], name='bugs_bug_bug_cod_8a1122_idx'),
        ),
    ]
