# Generated by Django 4.2.29 on 2026-09-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskcomment'),
        ('bugs', '0002_alter_bug_module_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='linked_task',
            field=models.ForeignKey(blank=True, help_text='Optional task or user story this defect originated from or blocks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['linked_task'], name='bugs_bug_linked__560d9d_idx'),
        ),
    ]
