# Generated by Django 4.2.29 on 2026-09-13 15:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('bugs', '0003_bug_linked_task_bug_bugs_bug_linked__560d9d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bugs.bug')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_attachments', to='files.storedfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
