"""
Django settings for AetherSpace project.
Generated by Antigravity - Senior Full-Stack Django Developer.
"""

import os
import sys
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment variables from .env
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-aetherspace-dev-phase1-seed-key-replace-in-production'
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 't')

allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,.onrender.com')
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_env.split(',') if h.strip()]

csrf_trusted_env = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://*.onrender.com,http://localhost,http://127.0.0.1')
CSRF_TRUSTED_ORIGINS = [orig.strip() for orig in csrf_trusted_env.split(',') if orig.strip()]

# Application definition
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'channels',

    # AetherSpace Modular Apps
    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'workspaces.apps.WorkspacesConfig',
    'tasks.apps.TasksConfig',
    'bugs.apps.BugsConfig',
    'chat.apps.ChatConfig',
    'meetings.apps.MeetingsConfig',
    'calendars.apps.CalendarsConfig',
    'files.apps.FilesConfig',
    'notifications.apps.NotificationsConfig',
    'admin_panel.apps.AdminPanelConfig',
    'user_settings.apps.UserSettingsConfig',
    'timetracking.apps.TimeTrackingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AetherSpaceGlobalErrorMiddleware',
    'core.middleware.ModuleMaintenanceMiddleware',
    'core.middleware.UserActivityMiddleware',
]

ROOT_URLCONF = 'aetherspace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.aetherspace_global_context',
                'workspaces.context_processors.workspace_context',
                'notifications.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'aetherspace.wsgi.application'
ASGI_APPLICATION = 'aetherspace.asgi.application'

REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# WebRTC STUN/TURN Configuration
DEFAULT_ICE_SERVERS = [
    {"urls": "stun:stun.l.google.com:19302"},
    {"urls": "stun:stun1.l.google.com:19302"},
    {"urls": "stun:stun2.l.google.com:19302"},
    {"urls": "stun:stun3.l.google.com:19302"},
    {"urls": "stun:stun4.l.google.com:19302"},
]

ICE_SERVERS_ENV = os.environ.get('ICE_SERVERS_JSON')
if ICE_SERVERS_ENV:
    try:
        import json
        WEBRTC_ICE_SERVERS = json.loads(ICE_SERVERS_ENV)
    except Exception:
        WEBRTC_ICE_SERVERS = DEFAULT_ICE_SERVERS
else:
    WEBRTC_ICE_SERVERS = DEFAULT_ICE_SERVERS

# Authoritative User Model
AUTH_USER_MODEL = 'accounts.User'

# Database configuration: Supabase PostgreSQL via DATABASE_URL
DATABASE_URL = os.environ.get('DATABASE_URL')
if not DATABASE_URL:
    raise ValueError(
        "DATABASE_URL environment variable is missing. "
        "AetherSpace strictly requires a configured Supabase PostgreSQL connection string."
    )

# Supabase Session/Transaction pooling:
# CONN_MAX_AGE defaults to 0 to prevent session pool exhaustion (EMAXCONNSESSION).
# DB_CONNECT_TIMEOUT defaults to 60s for reliable Render cold starts and deployment stability.
DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=int(os.environ.get('CONN_MAX_AGE', 0)),
        conn_health_checks=True,
    )
}

# Use fast isolated SQLite during test execution to prevent remote database lockouts or DNS failures
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }

# Supabase requires SSL connection and configured connect timeout for production / Render cold boots
if 'postgresql' in DATABASES['default'].get('ENGINE', ''):
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].setdefault('sslmode', 'require')
    DATABASES['default']['OPTIONS'].setdefault('connect_timeout', int(os.environ.get('DB_CONNECT_TIMEOUT', 60)))

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Media / Uploaded files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth redirection URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'workspaces:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.ContributorIdBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Supabase Configuration
SUPABASE_URL = os.environ.get('SUPABASE_URL', '')
SUPABASE_PUBLISHABLE_KEY = os.environ.get('SUPABASE_PUBLISHABLE_KEY', '')
SUPABASE_SECRET_KEY = os.environ.get('SUPABASE_SECRET_KEY', '')
SUPABASE_STORAGE_BUCKET = os.environ.get('SUPABASE_STORAGE_BUCKET', 'Aether Space 1')
SUPABASE_STORAGE_READY = os.environ.get('SUPABASE_STORAGE_READY', 'true').lower() in ('true', '1')

# Email Delivery Configuration (Environment-driven, clean console backend fallback in development)
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if os.environ.get('EMAIL_HOST')
    else 'notifications.email_backend.CleanConsoleEmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'AetherSpace <no-reply@aetherspace.dev>')

# Site URL Configuration (Used for absolute email CTA and notification links)
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000').rstrip('/')

# Secure Error Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'safe_standard': {
            'format': '[%(asctime)s] %(levelname)s in %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'safe_standard',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'aetherspace_debug.log',
            'formatter': 'safe_standard',
            'level': 'DEBUG',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'aetherspace.errors': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Production Security Headers & SSL Proxy Configuration
if not DEBUG and 'test' not in sys.argv:
    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True').lower() in ('true', '1')
    CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True').lower() in ('true', '1')
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True').lower() in ('true', '1')
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    hsts_seconds = int(os.environ.get('SECURE_HSTS_SECONDS', 31536000))
    if hsts_seconds > 0:
        SECURE_HSTS_SECONDS = hsts_seconds
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True

